spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/binapi
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: binapi-interface

server:
  port: 8001
  servlet:
    context-path: /api/interface

dubbo:
  application:
    name: binapi-interface
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

