spring:
  profiles:
    active: dev
  application:
    name: binapi-backend
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/binapi
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    publisher-confirm-type: correlated #开启发送端确认
    publisher-returns: true #开启发送端消息抵达队列的确认
    template:
      mandatory: true #只要抵达队列，以异步发送优先回调我们这个returnsConfirm
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
dubbo:
  application:
    name: binapi-backend-dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    parameters:
      namespace: 16239c21-ac42-46bc-a4e7-690e64272f5a
    check: false
  consumer:
    check: false
